aVBlogProject/aVBlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'), #this

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aVBlogProject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns=[
    path('bakim/', views.bakim, name='bakim' ),
    path('',views.post_list,name="post_list"),
    path('<slug:post>/',views.post_detail,name="post_detail"),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_tag'),


]

aVBlogProject/blog/models.py
# models
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager




class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

# post model
class Post(models.Model):
    STATUS_CHOICES = (
    ('draft', 'Taslak'),
    ('published', 'Yayında'),
    )

    title = models.CharField("Blog Başlığı", max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts', verbose_name='Yazar')
    body = RichTextUploadingField("İçerik")
    image = models.ImageField(upload_to='thumbnail/%Y/%m/%d/')
    tags = TaggableManager()
    
    publish = models.DateTimeField(default=timezone.now, verbose_name="Yayınlanma Tarihi")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    status = models.CharField("Yayınlanma Durumu", max_length=10,choices=STATUS_CHOICES,default='draft')

    class Meta:
        verbose_name_plural = "Blog Yazıları"
        verbose_name = "Yazı"
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title
    
    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])
    

aVBlogProject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.db.models import Count
from django.db.models import Q 
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
def post_list(request, tag_slug=None):
    posts = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    # search
    query = request.GET.get("q")
    if query:
        posts=Post.published.filter(Q(title__icontains=query) | Q(tags__name__icontains=query)).distinct()
            

    

    paginator = Paginator(posts, 10) # 10 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
        
    return render(request,'post_list.html',{'posts':posts, page:'pages', 'tag': tag})

def post_detail(request, post):
    post=get_object_or_404(Post,slug=post,status='published')
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:6]
    return render(request, 'post_detail.html',{'post':post,'similar_posts':similar_posts})


def bakim(request):
    return render(request, 'bakim.html')

aVBlogProject/templates/bakim.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
<title>Mehmet Solgun</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
body,h1 {font-family: "Raleway", sans-serif}
body, html {height: 100%}
.bgimg {
  background-image: url('https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg');
  min-height: 100%;
  background-position: center;
  background-size: cover;
}
</style>
</head>
<body>

<div class="bgimg w3-display-container w3-animate-opacity w3-text-white">
  <div class="w3-display-topleft w3-padding-large w3-xlarge">
    Mehmet Solgun
  </div>
  <div class="w3-display-middle">
    <h1 class="w3-jumbo w3-animate-top">Yakında</h1>
    <hr class="w3-border-grey" style="margin:auto;width:40%">
    <p class="w3-large w3-center">35 days left</p>
  </div>
  <div class="w3-display-bottomleft w3-padding-large">
    by <a href="https://www.mehmetsolgun.com.tr" target="_blank">Mehmet Solgun</a>
  </div>
</div>

</body>
</html>

aVBlogProject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Mehmet Solgun {% block title %}{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- static file -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
     <!-- highlight js -->
     <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/monokai-sublime.min.css">
     <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
     <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:post_list' %}">Mehmet Solgun</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/tag/kitap/' %}active{% endif %}" aria-current="page" href="{{ request.scheme }}://{{ request.get_host }}/tag/kitap/">Kitap</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/tag/film/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/film/">Film</a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% if request.path == '/tag/dizi/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/dizi/">Dizi</a>
          </li>
         
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Teknoloji
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item {% if request.path == '/tag/python/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/python/">Python</a>
            </li>
            
            <li>
              <a class="dropdown-item {% if request.path == '/tag/django/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/django/">Django</a>
            </li>

            <li>
              <a class="dropdown-item {% if request.path == '/tag/chatgpt/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/chatgpt/">ChatGPT</a>
            </li>
          
          </ul>
        </li>
      
        </ul>
      
        <form class="d-flex" action="/">
          <input class="form-control mr-0" type="search" value="{{request.GET.q}}" name="q" placeholder="Ara" aria-label="Search">
</form>
      </div>
    </div>
  </nav>



  <main class="container my-3">
    <!-- from here to -->
    <h2 class="my-3">
      {% if request.GET.q is not null %}
         "{{ request.GET.q }}" için arama sonuçları
      {% endif %}
    </h2>
    <!-- here -->

    {% block content %}

    {% endblock content %}
</main>

<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">© 2023 Mehmet Solgun</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <h4>Mehmet Solgun</h4>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link px-2 text-body-secondary">Anasayfa</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Hakkımda</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Giriş Yap</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Kayıt Ol</a></li>
    
    </ul>
  </footer>
</div>

  <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  
</body>
</html>

aVBlogProject/templates/pagination.html
{% if page.has_other_pages %}
  <ul class="pagination mt-3 mb-0">
    {% if page.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

aVBlogProject/templates/post_detail.html
{% extends 'base.html' %}

{% block title %} - {{post.title}}{% endblock title %}

{% block content %}
    <article>
        <figure>
         <img src="{{ post.image.url }}" class="rounded" alt="{{post.title}}">
        </figure>
        <div class="mt-3">
            <h1>{{post.title}}</h1>
            <p class="text-muted">
                Yayın Tarihi: {{ post.publish.date }} Yazar: <strong>{{ post.author }}</strong>
            </p>
        </div>

        <div class="article-body">
                {{post.body|safe}}
        </div>
        <p>
            <strong>Etiketler:</strong>
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_tag' tag.slug %}" class="link-light text-decoration-none badge bg-secondary">
                    {{tag.name}}
                </a>
                <!-- {% if not forloop.last %}, {% endif %} -->
            {% endfor %}
        </p>


    </article>

    <hr />

<div class="my-3">
    <h3>İlginizi Çekebilecek Yazılar:</h3>
</div>
<div class="row">
    {% for post in similar_posts %}
    <div class="col-md-6 col-sm-6 col-lg-4 mb-3">
        <div class="card border-0">
            <div class="ratio ratio-16x9">
                <img src="{{ post.image.url }}" class="rounded featured-image-list" alt="{{post.title}}">
            </div>
            <div class="card-body p-0 m-0 mt-2">
                <h2 class="card-title h6 my-0 py-0">
                    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                </h2>
                <p class="card-text">
                    <small class="text-muted">
                        <span>{{post.publish.date}} |
                            <b>{{post.author}}</b></span>

                        <!-- <a href="" class="badge badge-light text-muted">{{post.tags.all|join:" "}}</a> -->


                    </small>
                </p>
                <!-- <p>{{post.body|truncatechars:100|linebreaks}}</p> -->
            </div>
        </div>
    </div>
    {% empty %}
    <p class="text-muted">Henüz benzer bir yazı yok.</p>
    {% endfor %}
</div>
    
   
{% endblock content %}

aVBlogProject/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
{% if tag %}
<h2 class="mb-3"> "{{ tag.name }}" Etiketli Yazılar</h2>
{% endif %}
    {% for post in posts %}
    <div class="card mb-3">
        <div class="card-body">
            <div class="row g-0">
                <div class="col-md-5">
                    <div class="ratio ratio-16x9">
                        <img src="{{ post.image.url }}" class="rounded featured-image-list" alt="{{post.title}}">
                    </div>
                </div>
                <div class="col-md-7 ps-md-3 pt-3 pt-md-0 d-flex flex-column">
                    
                        <h2 class="card-title h5">
                                <a href="{{ post.get_absolute_url }}">
                                {{ post.title }}
                                </a>
                        </h2>

                        <div class="text-muted">
                            <small>
                                Yayın Tarihi: {{ post.publish.date }} Yazar: <strong>{{ post.author }}</strong>
                            </small>
                        </div>
                        
                        
                        <p class="card-text mb-auto py-2">{{ post.body|safe|striptags|truncatechars:100 }}</p>
                        
                    
               
                        <div>
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary btn-sm">Devamını oku.</a>
                        </div>
                
                </div>
            </div>
        </div>
    </div>
   
    {% endfor %}

    {% include "pagination.html" with page=posts %}


{% endblock content %}